<?php

/**
 * @file
 * Contains smart_content_smart_ip.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\smart_ip\SmartIp;

/**
 * Implements hook_help().
 */
function smart_content_smart_ip_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the smart_content_smart_ip module.
    case 'help.page.smart_content_smart_ip':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Smart Content Condition based on smart ip.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_block().
 */
function smart_content_smart_ip_preprocess_block(&$variables) {
  // Verify if the block is Smart Content Decision Block.
  if ($variables['base_plugin_id'] === 'smart_content_decision_block') {
    // Disable Cache for Smart Content Decision Blocks
    $variables['elements']['#cache']['max-age'] = 0;
    // Attach JS Library.
    $variables['#attached']['library'][] = 'smart_content_smart_ip/condtion.smart_ip';
    // Pass variable to drupalSettings.
    $ip_address = $_SERVER['HTTP_CF_CONNECTING_IP'];
    $variables['#attached']['drupalSettings']['smart_content_smart_ip'] = SmartIp::query($ip_address);
  }
}
